/**
 * FraudShield — Vercel Serverless API
 *
 * Standalone serverless function - NO native dependencies (no better-sqlite3).
 * Uses in-memory data seeded on cold start.
 * Works on Vercel without any native module compilation issues.
 */

import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';

const app = express();
app.use(cors());
app.use(express.json());

const JWT_SECRET = process.env.JWT_SECRET || 'fraudshield_secret_key_2025';
const JWT_EXPIRY = '8h';

// ══════════════════════════════════════════════════════════════════
//  IN-MEMORY DATA (seeded on cold start, no native deps needed)
// ══════════════════════════════════════════════════════════════════

const users = [
  { id: 1, username: 'admin', password: bcrypt.hashSync('admin123', 10), name: 'Admin User', role: 'admin' },
  { id: 2, username: 'analyst', password: bcrypt.hashSync('analyst123', 10), name: 'Risk Analyst', role: 'analyst' },
];

const names = ['James Volkov','Elena Chen','Viktor Martinez','Mei Al-Rashid','Carlos Nakamura','Fatima Johansson','Raj Okafor','Olga Petrov','Hassan Gupta','Linnea Schmidt','Diego Da Silva','Priya Müller','Chen Takahashi','Amara Fernandez','Sergei Kim'];
const jurisdictions = ['USA','UK','Switzerland','Singapore','Panama','Hong Kong','India','Germany','UAE','Nigeria'];
const currencies = ['USD','EUR','GBP','CHF','SGD','INR','JPY','AED','HKD'];
const channels = ['Mobile App','Web Portal','ATM','Branch','Wire Transfer','API'];
const typologies = ['Normal','Structuring','Smurfing','Layering','Round-Tripping','Phantom FDI'];
const pick = a => a[Math.floor(Math.random() * a.length)];
const randInt = (a, b) => Math.floor(a + Math.random() * (b - a + 1));

// Generate transactions
const transactions = [];
for (let i = 0; i < 200; i++) {
  const sender = pick(names);
  let receiver = pick(names);
  while (receiver === sender) receiver = pick(names);
  const isFraud = Math.random() < 0.18;
  const riskScore = isFraud ? randInt(55, 99) : randInt(3, 45);
  const typology = isFraud ? pick(typologies.filter(t => t !== 'Normal')) : 'Normal';
  transactions.push({
    txId: `TXN-${String(i + 1).padStart(5, '0')}`,
    amount: +(500 + Math.random() * 500000).toFixed(2),
    currency: pick(currencies),
    timestamp: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
    typology,
    isFraud,
    riskScore,
    status: riskScore > 80 ? 'Blocked' : riskScore > 50 ? 'Under Review' : 'Cleared',
    channel: pick(channels),
    deviceFingerprint: `DEV-${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
    ipAddress: `${randInt(10,200)}.${randInt(0,255)}.${randInt(0,255)}.${randInt(1,254)}`,
    senderId: `ACC-${String(randInt(1, 30)).padStart(4, '0')}`,
    senderName: sender,
    senderJurisdiction: pick(jurisdictions),
    receiverId: `ACC-${String(randInt(1, 30)).padStart(4, '0')}`,
    receiverName: receiver,
    receiverJurisdiction: pick(jurisdictions),
    senderAccountType: pick(['Savings', 'Checking', 'Investment', 'Corporate']),
  });
}
transactions.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

// Generate alerts
const alertSeverities = ['Critical', 'High', 'Medium', 'Low'];
const alerts = [];
for (let i = 0; i < 50; i++) {
  const sev = pick(alertSeverities);
  alerts.push({
    id: `ALT-${String(i + 1).padStart(4, '0')}`,
    type: pick(['Threshold Breach', 'Pattern Match', 'Velocity Check', 'Anomaly Detected', 'Sanctions Hit']),
    severity: sev,
    status: pick(['New', 'Investigating', 'Escalated', 'Resolved']),
    title: pick([
      'High-value transfer detected', 'Rapid succession of transactions',
      'Cross-border structuring pattern', 'Unusual account activity',
      'Sanctions screening match', 'Multiple accounts same device',
    ]),
    description: 'Automated alert generated by FraudShield neural engine.',
    accountId: `ACC-${String(randInt(1, 30)).padStart(4, '0')}`,
    timestamp: new Date(Date.now() - Math.random() * 14 * 86400000).toISOString(),
    assignedTo: pick(['Admin User', 'Risk Analyst', null]),
  });
}

// SAR Reports
const sarReports = [
  { id: 'SAR-001', status: 'Filed', title: 'Suspicious structuring activity', narrative: 'Multiple cash deposits below reporting threshold.', alertId: 'ALT-0001', filingDate: new Date().toISOString(), analyst: 'Admin User', totalAmount: 145000 },
  { id: 'SAR-002', status: 'Draft', title: 'Round-tripping through shell companies', narrative: 'Funds circulated through 3 offshore entities.', alertId: 'ALT-0005', filingDate: new Date().toISOString(), analyst: 'Risk Analyst', totalAmount: 890000 },
];

// ══════════════════════════════════════════════════════════════════
//  AUTH MIDDLEWARE
// ══════════════════════════════════════════════════════════════════

function requireAuth(req, res, next) {
  const header = req.headers.authorization;
  if (!header || !header.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Authentication required' });
  }
  try {
    req.user = jwt.verify(header.split(' ')[1], JWT_SECRET);
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }
}

function requireRole(...roles) {
  return (req, res, next) => {
    if (!req.user || !roles.includes(req.user.role)) {
      return res.status(403).json({ error: 'Insufficient permissions' });
    }
    next();
  };
}

// ══════════════════════════════════════════════════════════════════
//  ROUTES
// ══════════════════════════════════════════════════════════════════

// Health
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok', neo4j: false, mlApi: false,
    database: 'in-memory', environment: 'vercel',
    timestamp: new Date().toISOString(),
  });
});

// Login
app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body;
  if (!username || !password) return res.status(400).json({ error: 'Username and password required' });

  const user = users.find(u => u.username === username);
  if (!user || !bcrypt.compareSync(password, user.password)) {
    return res.status(401).json({ error: 'Invalid credentials' });
  }

  const token = jwt.sign(
    { id: user.id, username: user.username, name: user.name, role: user.role },
    JWT_SECRET, { expiresIn: JWT_EXPIRY }
  );
  res.json({ token, user: { id: user.id, username: user.username, name: user.name, role: user.role }, expiresIn: JWT_EXPIRY });
});

// Auth me
app.get('/api/auth/me', requireAuth, (req, res) => {
  res.json({ user: req.user });
});

// Transactions
app.get('/api/transactions', requireAuth, (req, res) => {
  let data = [...transactions];
  const { status, typology, search, limit = 200 } = req.query;
  if (status) data = data.filter(t => t.status === status);
  if (typology) data = data.filter(t => t.typology === typology);
  if (search) {
    const q = search.toLowerCase();
    data = data.filter(t => t.txId.toLowerCase().includes(q) || t.senderName.toLowerCase().includes(q) || t.receiverName.toLowerCase().includes(q));
  }
  res.json({ source: 'in-memory', data: data.slice(0, parseInt(limit)) });
});

// Accounts
app.get('/api/accounts', requireAuth, (req, res) => {
  const accounts = [];
  for (let i = 1; i <= 30; i++) {
    accounts.push({
      accountId: `ACC-${String(i).padStart(4, '0')}`,
      name: names[i % names.length],
      jurisdiction: jurisdictions[i % jurisdictions.length],
      type: pick(['Savings', 'Checking', 'Investment', 'Corporate']),
      riskTier: pick(['Low', 'Medium', 'High', 'Critical']),
      riskScore: randInt(5, 95),
      balance: +(10000 + Math.random() * 500000).toFixed(2),
    });
  }
  res.json({ source: 'in-memory', data: accounts });
});

// Graph
app.get('/api/graph', requireAuth, (req, res) => {
  res.json({ source: 'mock', nodes: [], links: [] });
});

// Alerts
app.get('/api/alerts', requireAuth, (req, res) => {
  let data = [...alerts];
  const { severity, status } = req.query;
  if (severity) data = data.filter(a => a.severity === severity);
  if (status) data = data.filter(a => a.status === status);
  res.json({ source: 'in-memory', data });
});

app.patch('/api/alerts/:id/status', requireAuth, requireRole('admin', 'analyst'), (req, res) => {
  const { status } = req.body;
  if (!['New', 'Investigating', 'Escalated', 'Resolved'].includes(status)) {
    return res.status(400).json({ error: 'Invalid status' });
  }
  const alert = alerts.find(a => a.id === req.params.id);
  if (alert) alert.status = status;
  res.json({ success: true, alertId: req.params.id, status });
});

// Analytics
app.get('/api/analytics', requireAuth, (req, res) => {
  const fraudTx = transactions.filter(t => t.isFraud).length;
  res.json({
    source: { neo4j: false, ml: false, db: 'in-memory' },
    mlMetrics: null,
    graphStats: { totalAccounts: 30, totalTx: transactions.length, fraudTx },
  });
});

// SAR Reports
app.get('/api/sar-reports', requireAuth, (req, res) => {
  res.json({ source: 'in-memory', data: sarReports });
});

app.post('/api/sar-reports', requireAuth, requireRole('admin', 'analyst'), (req, res) => {
  const { title, narrative, alertId, analyst, totalAmount } = req.body;
  const id = `SAR-${Date.now()}`;
  sarReports.push({ id, status: 'Draft', title, narrative, alertId, filingDate: new Date().toISOString(), analyst: analyst || req.user.name, totalAmount: totalAmount || 0 });
  res.status(201).json({ success: true, id });
});

// ML Score (stub)
app.post('/api/score', requireAuth, (req, res) => {
  res.status(503).json({ error: 'ML API not available in serverless mode' });
});

// Polling endpoint (replaces SSE for Vercel)
app.get('/api/stream/poll', requireAuth, (req, res) => {
  const count = parseInt(req.query.count) || 3;
  const txns = [];
  for (let i = 0; i < count; i++) {
    const sender = pick(names);
    let receiver = pick(names);
    while (receiver === sender) receiver = pick(names);
    const isFraud = Math.random() < 0.15;
    const riskScore = isFraud ? randInt(60, 99) : randInt(5, 45);
    txns.push({
      id: `TXN-${Date.now()}-${i}`,
      timestamp: new Date().toISOString(),
      sender: { name: sender, jurisdiction: pick(jurisdictions) },
      receiver: { name: receiver, jurisdiction: pick(jurisdictions) },
      amount: +(100 + Math.random() * 50000).toFixed(2),
      currency: pick(currencies),
      channel: pick(channels),
      riskScore,
      isFraud,
      typology: isFraud ? pick(['Structuring','Smurfing','Layering','Round-Tripping','Phantom FDI']) : 'Normal',
      status: riskScore > 80 ? 'Blocked' : riskScore > 50 ? 'Under Review' : 'Cleared',
    });
  }
  res.json(txns);
});

// SSE endpoint (works locally, will timeout on Vercel but that's OK — falls back to polling)
app.get('/api/stream/transactions', (req, res) => {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
  });
  res.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`);

  const interval = setInterval(() => {
    const sender = pick(names);
    let receiver = pick(names);
    while (receiver === sender) receiver = pick(names);
    const isFraud = Math.random() < 0.15;
    const riskScore = isFraud ? randInt(60, 99) : randInt(5, 45);
    const tx = {
      id: `TXN-${Date.now()}`,
      timestamp: new Date().toISOString(),
      sender: { name: sender, jurisdiction: pick(jurisdictions) },
      receiver: { name: receiver, jurisdiction: pick(jurisdictions) },
      amount: +(100 + Math.random() * 50000).toFixed(2),
      currency: pick(currencies),
      channel: pick(channels),
      riskScore, isFraud,
      typology: isFraud ? pick(['Structuring','Smurfing','Layering','Round-Tripping','Phantom FDI']) : 'Normal',
      status: riskScore > 80 ? 'Blocked' : riskScore > 50 ? 'Under Review' : 'Cleared',
    };
    res.write(`event: transaction\ndata: ${JSON.stringify(tx)}\n\n`);
  }, 3000);

  req.on('close', () => clearInterval(interval));
});

export default app;
